set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property PACKAGE_PIN E3 [get_ports CLK]

set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property PACKAGE_PIN M17 [get_ports RST]

set_property IOSTANDARD LVCMOS33 [get_ports Vga_hs]
set_property PACKAGE_PIN B11 [get_ports Vga_hs]
set_property IOSTANDARD LVCMOS33 [get_ports Vga_vs]
set_property PACKAGE_PIN B12 [get_ports Vga_vs]

set_property IOSTANDARD LVCMOS33 [get_ports Red[0]]
set_property PACKAGE_PIN A3 [get_ports Red[0]]
set_property IOSTANDARD LVCMOS33 [get_ports Red[1]]
set_property PACKAGE_PIN B4 [get_ports Red[1]]
set_property IOSTANDARD LVCMOS33 [get_ports Red[2]]
set_property PACKAGE_PIN C5 [get_ports Red[2]]
set_property IOSTANDARD LVCMOS33 [get_ports Red[3]]
set_property PACKAGE_PIN A4 [get_ports Red[3]]
set_property IOSTANDARD LVCMOS33 [get_ports Green[0]]
set_property PACKAGE_PIN C6 [get_ports Green[0]]
set_property IOSTANDARD LVCMOS33 [get_ports Green[1]]
set_property PACKAGE_PIN A5 [get_ports Green[1]]
set_property IOSTANDARD LVCMOS33 [get_ports Green[2]]
set_property PACKAGE_PIN B6 [get_ports Green[2]]
set_property IOSTANDARD LVCMOS33 [get_ports Green[3]]
set_property PACKAGE_PIN A6 [get_ports Green[3]]
set_property IOSTANDARD LVCMOS33 [get_ports Blue[0]]
set_property PACKAGE_PIN B7 [get_ports Blue[0]]
set_property IOSTANDARD LVCMOS33 [get_ports Blue[1]]
set_property PACKAGE_PIN C7 [get_ports Blue[1]]
set_property IOSTANDARD LVCMOS33 [get_ports Blue[2]]
set_property PACKAGE_PIN D7 [get_ports Blue[2]]
set_property IOSTANDARD LVCMOS33 [get_ports Blue[3]]
set_property PACKAGE_PIN D8 [get_ports Blue[3]]

set_property IOSTANDARD LVCMOS33 [get_ports down[0]]
set_property PACKAGE_PIN V10 [get_ports down[0]]
set_property IOSTANDARD LVCMOS33 [get_ports down[1]]
set_property PACKAGE_PIN U11 [get_ports down[1]]
set_property IOSTANDARD LVCMOS33 [get_ports down[2]]
set_property PACKAGE_PIN U12 [get_ports down[2]]
set_property IOSTANDARD LVCMOS33 [get_ports down[3]]
set_property PACKAGE_PIN H6 [get_ports down[3]]
set_property IOSTANDARD LVCMOS33 [get_ports down[4]]
set_property PACKAGE_PIN T13 [get_ports down[4]]
set_property IOSTANDARD LVCMOS33 [get_ports down[5]]
set_property PACKAGE_PIN R16 [get_ports down[5]]
set_property IOSTANDARD LVCMOS33 [get_ports down[6]]
set_property PACKAGE_PIN U8 [get_ports down[6]]
set_property IOSTANDARD LVCMOS33 [get_ports down[7]]
set_property PACKAGE_PIN T8 [get_ports down[7]]
set_property IOSTANDARD LVCMOS33 [get_ports down[8]]
set_property PACKAGE_PIN R13 [get_ports down[8]]
set_property IOSTANDARD LVCMOS33 [get_ports down[9]]
set_property PACKAGE_PIN U18 [get_ports down[9]]
set_property IOSTANDARD LVCMOS33 [get_ports down[10]]
set_property PACKAGE_PIN T18 [get_ports down[10]]
set_property IOSTANDARD LVCMOS33 [get_ports down[11]]
set_property PACKAGE_PIN R17 [get_ports down[11]]
set_property IOSTANDARD LVCMOS33 [get_ports down[12]]
set_property PACKAGE_PIN R15 [get_ports down[12]]
set_property IOSTANDARD LVCMOS33 [get_ports down[13]]
set_property PACKAGE_PIN M13 [get_ports down[13]]
set_property IOSTANDARD LVCMOS33 [get_ports down[14]]
set_property PACKAGE_PIN L16 [get_ports down[14]]
set_property IOSTANDARD LVCMOS33 [get_ports down[15]]
set_property PACKAGE_PIN J15 [get_ports down[15]]

set_property IOSTANDARD LVCMOS33 [get_ports MP3_CS]
set_property IOSTANDARD LVCMOS33 [get_ports MP3_DCS]
set_property IOSTANDARD LVCMOS33 [get_ports MP3_DREQ]
set_property IOSTANDARD LVCMOS33 [get_ports MP3_MISO]
set_property IOSTANDARD LVCMOS33 [get_ports MP3_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports MP3_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports MP3_RSET]
set_property PACKAGE_PIN F6 [get_ports MP3_RSET]
set_property PACKAGE_PIN K1 [get_ports MP3_DCS]
set_property PACKAGE_PIN J2 [get_ports MP3_DREQ]
set_property PACKAGE_PIN E7 [get_ports MP3_CS]
set_property PACKAGE_PIN J3 [get_ports MP3_SCLK]
set_property PACKAGE_PIN J4 [get_ports MP3_MOSI]
set_property PACKAGE_PIN E6 [get_ports MP3_MISO]

set_property IOSTANDARD LVCMOS33 [get_ports {Showdata[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Showdata[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Showdata[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Showdata[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Showdata[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Showdata[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Showdata[0]}]
set_property PACKAGE_PIN T10 [get_ports {Showdata[0]}]
set_property PACKAGE_PIN R10 [get_ports {Showdata[1]}]
set_property PACKAGE_PIN K16 [get_ports {Showdata[2]}]
set_property PACKAGE_PIN K13 [get_ports {Showdata[3]}]
set_property PACKAGE_PIN P15 [get_ports {Showdata[4]}]
set_property PACKAGE_PIN T11 [get_ports {Showdata[5]}]
set_property PACKAGE_PIN L18 [get_ports {Showdata[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SHF[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SHF[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SHF[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SHF[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SHF[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SHF[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SHF[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SHF[0]}]
set_property PACKAGE_PIN J17 [get_ports {SHF[0]}]
set_property PACKAGE_PIN J18 [get_ports {SHF[1]}]
set_property PACKAGE_PIN T9 [get_ports {SHF[2]}]
set_property PACKAGE_PIN J14 [get_ports {SHF[3]}]
set_property PACKAGE_PIN P14 [get_ports {SHF[4]}]
set_property PACKAGE_PIN T14 [get_ports {SHF[5]}]
set_property PACKAGE_PIN K2 [get_ports {SHF[6]}]
set_property PACKAGE_PIN U13 [get_ports {SHF[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports Dp]
set_property PACKAGE_PIN H15 [get_ports Dp]

set_property IOSTANDARD LVCMOS33 [get_ports Bluetooth_rxt]
set_property PACKAGE_PIN H14 [get_ports Bluetooth_rxt]

set_property IOSTANDARD LVCMOS33 [get_ports ledh]
set_property PACKAGE_PIN V11 [get_ports ledh]

set_property IOSTANDARD LVCMOS33 [get_ports ledm]
set_property PACKAGE_PIN V14 [get_ports ledm]

set_property IOSTANDARD LVCMOS33 [get_ports ledg]
set_property PACKAGE_PIN V12 [get_ports ledg]

set_property IOSTANDARD LVCMOS33 [get_ports ledmu[3]]
set_property PACKAGE_PIN N14 [get_ports ledmu[3]]

set_property IOSTANDARD LVCMOS33 [get_ports ledmu[2]]
set_property PACKAGE_PIN J13 [get_ports ledmu[2]]

set_property IOSTANDARD LVCMOS33 [get_ports ledmu[1]]
set_property PACKAGE_PIN K15 [get_ports ledmu[1]]

set_property IOSTANDARD LVCMOS33 [get_ports ledmu[0]]
set_property PACKAGE_PIN H17 [get_ports ledmu[0]]

set_property IOSTANDARD LVCMOS33 [get_ports St]
set_property PACKAGE_PIN N17 [get_ports St]

set_property IOSTANDARD LVCMOS33 [get_ports Ct]
set_property PACKAGE_PIN P17 [get_ports Ct]

set_property IOSTANDARD LVCMOS33 [get_ports out[0]]
set_property PACKAGE_PIN R18 [get_ports out[0]]
set_property IOSTANDARD LVCMOS33 [get_ports out[1]]
set_property PACKAGE_PIN V17 [get_ports out[1]]
set_property IOSTANDARD LVCMOS33 [get_ports out[2]]
set_property PACKAGE_PIN U17 [get_ports out[2]]
set_property IOSTANDARD LVCMOS33 [get_ports out[3]]
set_property PACKAGE_PIN U16 [get_ports out[3]]
set_property IOSTANDARD LVCMOS33 [get_ports out[4]]
set_property PACKAGE_PIN V16 [get_ports out[4]]
set_property IOSTANDARD LVCMOS33 [get_ports out[5]]
set_property PACKAGE_PIN T15 [get_ports out[5]]
set_property IOSTANDARD LVCMOS33 [get_ports out[6]]
set_property PACKAGE_PIN U14 [get_ports out[6]]
set_property IOSTANDARD LVCMOS33 [get_ports out[7]]
set_property PACKAGE_PIN T16 [get_ports out[7]]